team-dopamine/husk-was

build.gradle
src/main/java/kr/husk/infrastructure/config/SwaggerConfig.java

RESTful API 표준화 및 문서화, Front-End와의 커뮤니케이션 향상을 위한 OAS 문서 연동.
SwaggerConfig 설정 파일 작성 및 관련 외부 의존성 추가.
정상적으로 localhost:8080/swagger-ui/index.html 페이지 접속이 되는 것을 확인했습니다.
JWT 기반 보안 인증은 적용하지 않았습니다.

RESTful API 문서화 및 표준화를 위한 Swagger 연동

---

build.gradle
src/main/java/kr/husk/application/auth/dto/SendAuthCode.java
src/main/java/kr/husk/application/auth/dto/SendAuthCodeDto.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/domain/auth/repository/UserRepository.java
src/main/java/kr/husk/domain/auth/service/UserService.java
src/main/java/kr/husk/infrastructure/config/SecurityConfig.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java
src/main/resources/application.yml
src/test/java/kr/husk/presentation/rest/AuthControllerTest.java

- 회원 가입 이전 계정 검증 여부 필요성 대두
- 이메일 검증을 통한 중복 회원 최소화 및 계정 유효성 검증
1. `UserService` (도메인 서비스) - 회원 존재 여부 검증
2. `AuthService` (유스케이스) - 인증 코드 저장 및 이메일 전송
3. `AuthController` (REST API) - 인증 코드 전송 API 구현
4. `AuthApi` (OAS Docs) - 인증 코드 전송 API Docs 작성
- `SecurityConfig` 정의하여 swagger 및 특정 api 요청 시 인증 생략하도록 설정하였습니다.
- Swagger의 경우 CSRF 공격에 대해 취약해지기 때문에 추후 접근 가능한 계정을 별도로 생성해놓아도 좋을 것 같아요.
- [참고자료](https://velog.io/@tjddus0302/Spring-Boot-%EB%A9%94%EC%9D%BC-%EB%B0%9C%EC%86%A1-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0-Gmail)에서 Google Mail 설정 참고하였습니다. 
- API를 구현하고 보니 GlobalExceptionHandler를 통한 예외 핸들링을 하면 좋을 것 같다는 생각이 드네요, 이야기 나눠봐도 좋을 것 같습니다.
- 테스트 코드 실행 시 body 검증이 올바르게 되지 않고 있어, 해당 부분 제외하였습니다. 추후 테스트 환경에 대해 이야기 나눠본 후 수정하면 좋을 것 같습니다.

인증 코드 전송 API 구현

---

src/main/java/kr/husk/application/auth/dto/VerifyAuthCodeDto.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/domain/auth/repository/AuthCodeRepository.java
src/main/java/kr/husk/infrastructure/config/AuthConfig.java
src/main/java/kr/husk/infrastructure/config/SecurityConfig.java
src/main/java/kr/husk/infrastructure/persistence/ConcurrentMapAuthCodeRepository.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java
src/test/java/kr/husk/presentation/rest/AuthControllerTest.java

- 회원 가입을 위한 이메일 인증 후 이를 검증(본인 확인)하기 위한 기능 필요성 대두
- 인증 코드 검증 API 구현
- 인증 코드 검증 API CSRF 허용
- 인증 코드 검증 성공/실패 응답 확인 했습니다!
- 현재 테스트 코드의 경우, 커버리지가 많이 부족하다고 생각해서 이에 대해 추후 방안을 세워봤으면 좋겠습니다!
- API 응답 성공 메시지를 관리하는 주체를 어디에 두는 게 좋을 지 고민이 됩니다.

feature/HK-46: 인증 코드 검증 API 구현

---

build.gradle
src/main/resources/application.yml

- WAS 구성 데이터 및 중요 정보를 중앙화 하기 위해 Parameter Store 도입.
- Parameter Store 적용으로 WAS의 구성을 안전하고 쉽게 관리.
- application.yml 및 환경 변수 최신화에 대한 편의성 추구.
- Parameter Store 관련 의존성 주입
- application.yml 환경 변수 값을 AWS Parameter Store에서 파라미터 생성을 통해 치환함.
- 의존성 추가 및 application.yml 수정만 하다보니 line수는 적습니다!
- Slack에서 말씀드렸던 이슈는 AWS CLI를 설치하여 Local에서 access-key 및 secret-key를 적용하니 해결된 것으로 생각됩니다.
- 특별히 설정을 수정하고 추가했던 부분은 없었기 때문인데 해당 PR이 merge 되면 다른 환경에서 확인해보도록 하겠습니다.
- Parameter Store에 Parameter 생성 시 이름 관련하여 Convention이 필요할 것 같습니다. 
- 현재는 설정 값이 많지 않아서 우선 제 임의로 작성을 했는데 추후 `GlobalException`에 대한 작업을 함께 진행하면서 얘기나눠 보면 좋을 것 같아요 😄

WAS 구성 데이터 및 중요 정보 중앙화를 위한 AWS Parameter Store 적용

---

build.gradle
src/main/java/kr/husk/HuskApplication.java
src/main/java/kr/husk/application/auth/dto/SignUpDto.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/application/auth/service/UserService.java
src/main/java/kr/husk/common/entity/BaseEntity.java
src/main/java/kr/husk/domain/auth/entity/User.java
src/main/java/kr/husk/domain/auth/service/UserService.java
src/main/java/kr/husk/infrastructure/config/AuthConfig.java
src/main/java/kr/husk/infrastructure/config/SecurityConfig.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java
src/test/java/kr/husk/presentation/rest/AuthControllerTest.java

- [HK-41 | [BE] 회원 가입 API 구현](https://team-dopamine.atlassian.net/browse/HK-41?atlOrigin=eyJpIjoiNGEzOTdkYmJlMzg0NDBkZjg3NTYxZDU5MmNhZGY4NDAiLCJwIjoiaiJ9)
- 서비스 이용을 위한 일반 사용자(Third-Party Platform 회원이 아닌)의 회원가입 기능 제공 필요성 대두
- 사용자 생성 로직 구현
- 기본적으로는 `OAuthProvider.NONE`으로 저장되도록 구현 (b5e5e33b7cade89ff8dcad2674dbcade459e604e)
- 회원가입 Usecase 로직 구현
- 비밀번호 형식(대/소문자 8~16글자, 숫자 및 특수문자 포함) 적용 (1b32dcb535a52a5522ea135f2ce66f7497337c89)
- 비밀번호 단방향 암호화 적용 (926e397dade748d564a86a8b13a580a6cc994e16)
- 회원가입 API CSRF 허용 (e7ebb9a7a90895de401dff3055cf34fdb9fc5d14)
- `PropertyValueException` 이슈 해결 (71d28dfa62699c33173906491efcd8b373ca262b)
```plaintext
org.hibernate.PropertyValueException: not-null property references a null or transient value : kr.husk.domain.auth.entity.User.createdAt
at …
```

Feature(HK-41): 일반 회원가입 API 구현

---

src/main/java/kr/husk/common/exception/ExceptionCode.java
src/main/java/kr/husk/common/exception/ExceptionResponse.java
src/main/java/kr/husk/common/exception/GlobalException.java
src/main/java/kr/husk/common/exception/GlobalExceptionHandler.java

- 각 도메인별 API에 대한 예외 처리 일원화
- 예외 전달 시 좀 더 상세하고 명시적인 정보 제공 필요
- 예외 발생 후 처리 작업성 향상을 위함                                                                                 
- `Custom Exception` 구현
- `GlobalException`, `GlobalExceptionHandler`, `ExceptionCode`, `ExceptionResponse`를 구현하여 예외 처리를 일원화 함.
- 예외 발생 시 Custom Exception에서 해당 예외를 catch하여 커스터마이징 된 예외를 발생시키도록 함.
- 참고: https://mangkyu.tistory.com/204 https://mangkyu.tistory.com/205
- (위 블로그의 글이 잘 설명되어 있어서 별도로 SpringBoot에서 예외 처리하는 로직 공부하실 때 도움이 되실 것 같아요!)
- 위 사진은 이메일 인증 코드 실패 시 Custom Exception으로 처리된 것 입니다. 
- 기존의 예외는 별도의 PR로 분리하려고 합니다! 추후 PR 올리도록 하겠습니다
- 제가 전에 사용했던 방식으로 구현했는데, 혹시 추가적으로 피드백 주신다면 수정하겠습니다!

chore/HK-42: 공통 예외 처리를 위한 Custom Exception 구현

---

src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/domain/auth/exception/AuthExceptionCode.java
src/main/java/kr/husk/domain/auth/exception/UserExceptionCode.java

- 이전 작업으로 공통 예외 처리를 위해 Custom Exception을 구현(https://github.com/team-dopamine/husk-was/pull/13)
- 기존에 만들어진 API(이메일 전송, 인증,  회원가입)에 Custom Exception 적용을 위한 Global Exception 적용
- User 관련 예외 코드 추가 (7da6e08819aa2f2aa10716e0e3b9693b91f0cd69)
- Auth 관련 예외 코드 추가 (e24c4ef1b4ac9cf423691067f208b665de8a6ac4)
- AuthService에 위의 예외 코드 적용 (c77114ada5e661001eb598e15358ef8ae39b0ec1)
위 이미지는 Custom Exception PR에 있지만, 본 PR의 적용 사항이라 여기에도 올려놓겠습니다!
우선은 구현된 API에 대해서만 예외 코드를 만들어 적용해놓았습니다. 추후에 개발되는 API에는 작업자가 예외 코드를 별도로 만들고 PR을 통해서 네이밍, 에러 코드 등을 이야기 해보면 좋을 것 같습니다!

Feature(HK-73): Global Exception 구현 및 적용

---

build.gradle
src/main/java/kr/husk/application/auth/dto/JwtTokenDto.java
src/main/java/kr/husk/application/auth/dto/SignInDto.java
src/main/java/kr/husk/application/auth/dto/SignUpDto.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/common/jwt/filter/JwtAuthenticationFilter.java
src/main/java/kr/husk/common/jwt/util/JwtProvider.java
src/main/java/kr/husk/domain/auth/entity/User.java
src/main/java/kr/husk/domain/auth/exception/AuthExceptionCode.java
src/main/java/kr/husk/domain/auth/exception/UserExceptionCode.java
src/main/java/kr/husk/domain/auth/service/UserService.java
src/main/java/kr/husk/infrastructure/config/SecurityConfig.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java
src/main/resources/application.yml

- [HK-74](https://team-dopamine.atlassian.net/browse/HK-74?atlOrigin=eyJpIjoiYjc5NGE2YmZiZmI3NGQ5NWIzMWNjMDBlZGIxYzNhY2MiLCJwIjoiaiJ9)
- OAuth가 아닌 일반 계정에 대한 로그인 기능 필요
- JWT 기반 인증 방식 선정. 
- `JwtAuthenticationFilter`, `JwtProvider` 객체 구현
- `/auth/sign-in` end point 접근 허용
- `access token`, `refresh token`을 활용하여 인증 비즈니스 로직 구현
- Jwt 관련 환경 변수 AWS Parameter Store 등록
- 일반 로그인 API 구현
<details>
<summary>API 테스트 결과</summary>
</details>
- JWT 관련 환경변수는 `Parameter Store`에 등록되어 있습니다!
- 일반 로그인 API 구현이 거의 처음이라 최대한 여러 자료를 보면서 구현했지만, 부족한 부분이 많을 것이라 예상됩니다! 그런 부분은 코멘트 남겨주시면 감사하겠습니다!
- `UserDetails`, `UserDetailsService`, `AuthenticationProvider` 등을 별도로 구현하지는 않았는데 문제가 되지는 않는지 궁금합니다.
[HK-74]: https://team-dopamine.atlassian.net/browse/HK-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

Feature(HK-74): 서비스 일반 계정 로그인을 위한 API 구현

---

src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/common/jwt/util/JwtProvider.java
src/main/java/kr/husk/domain/auth/repository/RefreshTokenRepository.java
src/main/java/kr/husk/infrastructure/persistence/ConcurrentMapRefreshRefreshTokenRepository.java
src/main/java/kr/husk/infrastructure/persistence/ConcurrentMapRefreshTokenRepository.java

- [Jira(HK-83)](https://team-dopamine.atlassian.net/browse/HK-83?atlOrigin=eyJpIjoiZWNkNmY5OGQ1YWQ3NDI2YWI3NGFhMzA2ODEyODQzYjciLCJwIjoiaiJ9)
- JWT를 활용한 인증 방식을 채택하여 Sign-In API 구현 (#17)
- JWT의 Refresh Token을 관리하는 관련 로직 필요
- `AuthCode`와 같이 `ConcurrentHashMap` 자료구조를 사용하여 일반 이메일 계정에 따른 refresh token 관리
- `refresh token` 생성, 조회, 삭제 관련 기능 구현
- `Sign-In` 진행 시 `access token`과 `refresh token` 생성 후 `ConcurrentHashMap`에 `refresh token 저장`
- `refresh token`을 `ConcurrentHashMap`에 저장한 후 스케줄링을 통해 만료시간이 되면 자동으로 `refresh token` 삭제
- `AuthService`의 `signIn` 진행 시 기존에 저장된 `refresh token`이 존재하는지 확인하는 메소드가 필요한지 궁금하네요!
- 추후 `signOut` API 개발 시 `refresh token`을 삭제하도록록 구현할 예정인데 그럼에도 확인이 필요한지 궁금합니다!

Feature(HK-83): JWT 인증 관련 Refresh Token 로직 추가

---

src/main/java/kr/husk/application/auth/config/GoogleConfig.java
src/main/java/kr/husk/application/auth/dto/SignInDto.java
src/main/java/kr/husk/application/auth/service/GoogleOAuthService.java
src/main/java/kr/husk/domain/auth/exception/AuthExceptionCode.java
src/main/java/kr/husk/domain/auth/repository/UserRepository.java
src/main/java/kr/husk/domain/auth/service/UserService.java
src/main/java/kr/husk/infrastructure/config/SecurityConfig.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java
src/main/resources/application.yml

- [HK-75](https://team-dopamine.atlassian.net/browse/HK-75?atlOrigin=eyJpIjoiNGQ2NWViNmQ0MzRjNDA0NzgxNzZhYzRlN2ZiYzE0Y2UiLCJwIjoiaiJ9)
- 편리한 서비스 이용을 위한 `Google OAuth2.0` 로그인 구현
- 팀 계정으로 Google OAuth 프로젝트 등록 및 클라이언트 ID, Secret 발급.
- `auth/sign-in/google` Endpoint 등록.
- `Google`로부터 발급받은 액세스 토큰 확인 후 `WAS`에서 액세스 토큰 및 리프레시 토큰 발행
- OAuth로 로그인하는 이메일과 일반 회원가입을 통해 가입된 이메일이 중복되는 경우 기존의 `UserService`의 `isExist()` 메소드를 사용하는 경우 오류 발생.
- `UserRepository`에서 `findByEmailAndOAuthProvider()` 메소드로 이메일 존재 여부를 확인하는데 이 부분에서 JPA에서 메소드명에 따른 쿼리를 생성하는 부분에서도 문제가 생겨 `@Query`을 사용하여 처리하도록 수정 및 구현하였습니다.(038c5adf95970a382d14fe381671be0882aad157)
- 해당 오류에 대한 처리는 `JIRA`([HK-75](https://team-dopamine.atlassian.net/browse/HK-75?))에 정리해두었으니 읽어보시면 좋을 것 같습니다!
- Google OAuth 구현을 위해 공부한 자료도 위의 JIRA에 댓글로 남겨놓았습니다!
- 추가로 지난 일반 …

Feature(HK-75): Google OAuth 로그인 기능 구현

---

src/main/java/kr/husk/application/auth/config/GitHubConfig.java
src/main/java/kr/husk/application/auth/service/GitHubOAuthService.java
src/main/java/kr/husk/presentation/rest/AuthController.java
src/main/resources/application.yml

- ([HK-76](https://team-dopamine.atlassian.net/browse/HK-76?atlOrigin=eyJpIjoiZjYzMzBkMDZhNGE3NDg0NWE4MTU1OTU0YzZkZmFhMzciLCJwIjoiaiJ9))
- 편리한 서비스 이용을 위한 `GitHub OAuth2.0` 로그인 구현
- GitHub의 OAuth Apps를 통해 프로젝트 생성 후 `클라이언트 ID`, `클라이언트 Secret` 발급 및 `Redirect URI` 등록
- GitHub OAuth의 경우`userInfo`의 `email`이 `null`로 응답되는 경우가 있습니다. 따라서, `GitHub username` + `@github.com` 을 결합하여 이메일로 만들도록 구현.
- ex) 주희님의 경우라면 `jujuj@github.com`으로 저장됩니다!
- API 테스트 결과
- Redirect URI의 경우 같이 OAuth 로그인 연동하실 때, 같이 맞춰보면서 하면 될 것 같습니다!
[HK-76]: https://team-dopamine.atlassian.net/browse/HK-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature(HK-76): GitHub OAuth 로그인 기능 구현

---

src/main/java/kr/husk/application/auth/dto/SignOutDto.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/common/jwt/filter/JwtAuthenticationFilter.java
src/main/java/kr/husk/common/jwt/util/JwtProvider.java
src/main/java/kr/husk/domain/auth/exception/AuthExceptionCode.java
src/main/java/kr/husk/infrastructure/persistence/ConcurrentMapRefreshTokenRepository.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java

- 서비스 사용자들의 안전한 계정 관리를 위한 로그아웃 API 구현 필요성 대두
- JWT 토큰 관리 및 악용 우려에 대비 할 필요성이 있음.
- `/auth/sign-out` 을 통한 `SignOut` API 구현(5d4a61baac3956e5ebec43294862c9be66f4a4ac)
- `Access Token`을 통해 서버에 저장된 사용자의 `Refresh Token` 삭제(88e0721c4dc44c40d98408bd9d28980468901295)
- `OAuth2.0 (Google, GitHub) SignIn`과 `서비스 자체 SignIn` 을 중복 허용하는 경우에 대해서 문제가 발생
- Jwt Token에 OAuth Platform 제공자인 `Provider`를 추가하여 `Provider` 검사를 이용하여 이메일 중복을 허용할 수 있으나 현재 작성된 코드를 다소 수정해야함.
- 코드 수정과 더불어 현재는 `Refresh Token(value)`을 `email(key)`로 조회하는데 이중 로그인이 되어있는 경우`(ex. Google, 일반 로그인)` 로그아웃 시 처음에 로그인한 플랫폼으로 로그아웃 불가능(`Refresh Token이 유효하지 않음`)
- 따라서, 사용자의 경험과 보안을 단순화 하기 위해서 `중복 이메일을 통한 로그인 및 회원가입을 불허함`
- 스크럼 때 말씀드린 것처럼, 우선은 위의 방향으로 진행하려고 합니다. 하지만, `Back-End` 상황에 따라 기존의 방향을 유지하는 쪽으로 진행할 수 있을 것 같습니다!
<details>
<summary>일반 계정 로그아웃 …

Feature(HK-90): 서비스 로그아웃 API 구현

---

src/main/java/kr/husk/application/auth/dto/ChangePasswordDto.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/domain/auth/entity/User.java
src/main/java/kr/husk/domain/auth/exception/AuthExceptionCode.java
src/main/java/kr/husk/domain/auth/exception/UserExceptionCode.java
src/main/java/kr/husk/domain/auth/service/UserService.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java

- 사용자 계정의 보안을 위한 비밀번호 변경 API 필요
- 비밀번호 변경에 대한 DTO 객체 구현 (2cc7ff79304491f40caf1513fd817542746686c1)
- 현재 비밀번호, 새로운 비밀번호, 비밀번호 확인 (3가지를 확인받음)
- 관련 예외코드 추가 (f9d7f5dc9cd06e2929f7b61c4643fb5d5677c084)
- User Entity의 비밀번호 변경 메소드 추가 (dc0dba1f399ed139376318667c98e5e7a037a168)
- 비밀번호 변경 시 `사용자가 입력한 새로운 비밀번호로 설정 후 인코딩 실시`
- 현재 특수문자에 대한 검증이 제대로 이루어지고 있지 않습니다. `authorization`에 대한 `Backlog` 개발이 완료된다면 전반적인 코드를 확인해보고 리팩토링 할 예정입니다.
- 정규표현식에서 `-`가 중간에 있어서 생기는 문제로 확인했음

Feature(HK-95): 일반 사용자 비밀번호 변경 API 구현

---

src/main/java/kr/husk/application/auth/dto/EmailDto.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/infrastructure/config/SecurityConfig.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java
src/test/java/kr/husk/presentation/rest/AuthControllerTest.java

- 해당 서비스 사용자가 비밀번호를 잃어버린 경우, 사용자가 로그인 후 비밀번호를 재설정 할 수 있도록 해야함.
- `사용자는 이메일 인증 후 임시 비밀번호를 이메일로 받을 수 있음.`
- 기존의 비밀번호 규칙을 지켜서 랜덤 문자열 생성(`특수문자 1개 이상, 영어 대/소문자 각 1개 이상, 숫자 1개 이상`) (3f30a8b47be74755df015f0d631a3fc253a79e21)
- 임시 비밀번호 발급이 기존의 인증 코드 전송과 로직이 동일하여 기존의 인증 코드 전송을 위한 dto에 대해 리팩토링 진행 (10424a09d079eccf07654bf6770a1c4decb26818)
- `SendAuthCodeDto → EmailDto`로 수정
- `AuthService` 에서의 `sendEmail()` 메소드도 인증 코드에 대한 내용으로만 설정되어 있었으나 해당 메소드 호출 시 내용을 설정할 수 있도록 수정
- X

Feature(HK-96): 임시 비밀번호 발급 API 구현

---

src/main/java/kr/husk/application/auth/config/GitHubConfig.java
src/main/java/kr/husk/application/auth/config/GoogleConfig.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/application/auth/service/GitHubOAuthService.java
src/main/java/kr/husk/application/auth/service/GoogleOAuthService.java
src/main/java/kr/husk/common/entity/BaseEntity.java
src/main/java/kr/husk/domain/auth/exception/AuthExceptionCode.java
src/main/java/kr/husk/domain/auth/exception/UserExceptionCode.java
src/main/java/kr/husk/domain/auth/repository/OAuthTokenRepository.java
src/main/java/kr/husk/domain/auth/repository/UserRepository.java
src/main/java/kr/husk/domain/auth/service/UserService.java
src/main/java/kr/husk/infrastructure/persistence/ConcurrentMapOAuthTokenRepository.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java
src/main/resources/application.yml

- 서비스 사용자의 계정 탈퇴 API 구현 필요
- 데이터의 무결성 및 결함을 최소화 하기 위해 `soft delete` 방식으로 탈퇴 로직 구현
- 사용자의 회원 상태에서 `deleted_at`을 설정함으로써 회원 탈퇴 시 `soft delete` 처리
- `OAuth 사용자`의 경우 로그인 시 `OAuth 제공 플랫폼`으로부터 받은 `액세스 코드를 통해 탈퇴 처리`함.
- 탈퇴 후 30일이내 재가입(OAuth 계정의 경우 재로그인) 시 계정 복구. 
- `Google`, `GitHub`, `일반 계정` 모두 테스트 완료했으며 문제없이 동작함을 확인했습니다.
- 코드를 리팩토링 해야할 부분이 많은데 앞선 PR에서 말씀드렸듯 `authorization` 스토리 마무리 후 진행할 예정입니다.

Feature(HK-97): 서비스 사용자의 회원 탈퇴 API 구현

---

src/main/java/kr/husk/application/auth/dto/ChangePasswordDto.java
src/main/java/kr/husk/application/auth/dto/SignInDto.java
src/main/java/kr/husk/application/auth/dto/SignUpDto.java
src/main/java/kr/husk/application/auth/dto/WithdrawDto.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/application/auth/service/GitHubOAuthService.java
src/main/java/kr/husk/application/auth/service/GoogleOAuthService.java
src/main/java/kr/husk/domain/auth/exception/AuthExceptionCode.java
src/main/java/kr/husk/presentation/api/AuthApi.java

- Back-End의 MVP 1.0 Authorization 도메인의 API 개발 완료.
- Authorization API 개발 과정에서 작성한 코드 정리 및 오타 수정
- 회원 탈퇴 시 message 반환 → WithdrawDto 객체를 추가하여 dto 객체로 반환 (3e4e4c7299482e9e4a59c5e96e611b963c23f6c4)
- Swagger `Sign-In` 스키마 수정
- GitHubOAuthService 및 GoogleOAuthService에서 동일한 예외 코드를 반환하도록 일치시킴. (52603a89e949c6bd54fe8e7606ca527bdf1cd900)
- X

Refactor(HK-104): Authorization Code Refactoring

---

src/main/java/kr/husk/application/keychain/dto/KeyChainDto.java
src/main/java/kr/husk/common/service/EncryptionService.java
src/main/java/kr/husk/domain/keychain/entity/KeyChain.java
src/main/java/kr/husk/domain/keychain/repository/KeyChainRepository.java
src/main/java/kr/husk/domain/keychain/service/KeyChainService.java
src/main/java/kr/husk/infrastructure/config/EncryptionConfig.java
src/main/java/kr/husk/presentation/api/KeyChainApi.java
src/main/java/kr/husk/presentation/rest/KeyChainController.java
src/main/resources/application.yml

- 서비스 사용자의 편의를 위한 키체인(키페어) 저장 기능 필요성 대두
- ssh connection 시 필요한 키체인(키페어)를 저장하기 위한 API 구현 필요
- `keychain` 등록 시 보안을 위한 암호화 설정 (2419702b56a431fe4749b18c5cd1cda769027271)
- 기존 `keychain` 객체의 content 크기가 1024로 키페어의 크기보다 작아서 저장하지 못하는 문제가 발생하여 컬럼 속성을 `TEXT`로 변경 (caf12af3a71e15175a5cb8165ccc50c7f11b6c59)
- 이외 controller, service, repository, dto 생성 (이외 커밋 참고)
- 더 좋은 방법이나 궁금한 부분, 오타 및 불필요한 부분이 있는지 확인 부탁드립니다!
<details>
<summary>API 테스트</summary>
</details>

Feature(HK-109): 키체인(키페어) 등록을 위한 API 구현

---

src/main/java/kr/husk/application/keychain/dto/KeyChainDto.java
src/main/java/kr/husk/common/entity/BaseEntity.java
src/main/java/kr/husk/domain/keychain/entity/KeyChain.java
src/main/java/kr/husk/domain/keychain/service/KeyChainService.java
src/main/java/kr/husk/presentation/api/KeyChainApi.java
src/main/java/kr/husk/presentation/rest/KeyChainController.java

- 서비스 DashBoard 기능을 위한 키체인 조회 API 구현
- 사용자가 등록한 키체인의 목록을 확인할 수 있음.
- 관련 DTO 객체 추가 (8e9d33c961ce448146ec566ffa2fa94c009cb431)
- Controller, Service 로직 추가 (b09bc98a81fada7574089a1e6160f9d7dad6dd0b)
- 추가적으로, 말씀드린대로 키체인의 `content`는 별도의 복호화 버튼을 구현하고 해당 버튼을 누른 경우 `content`가 보여지도록 합니다.
<details> 
<summary>API 테스트 결과</summary>
</details>

Feature(HK-113): 키체인 조회 API 구현

---

src/main/java/kr/husk/application/keychain/dto/KeyChainDto.java
src/main/java/kr/husk/domain/keychain/entity/KeyChain.java
src/main/java/kr/husk/domain/keychain/exception/KeyChainExceptionCode.java
src/main/java/kr/husk/domain/keychain/service/KeyChainService.java
src/main/java/kr/husk/presentation/api/KeyChainApi.java
src/main/java/kr/husk/presentation/rest/KeyChainController.java

- 사용자의 서비스 사용 편의성을 위한 키체인 수정 API 구현 필요
- 기존의 `KeyChainDto.KeyChainInfo` 클래스에 `content` 변수를 추가하여 API 요청 시 사용. (aa1b8338d9868c598b0e67053de6308f494c31b8)
- 수정된 키체인을 반영하기 위한 `Entity` 클래스 내의 `change` 관련 메소드 추가. (7149a7f7a72177a6061e9c4f96bacace797b291c)
- 문서화를 위한 swagger api 작성, controller 및 service 클래스 내 수정 관련 메소드 추가. (a506159737981e27f67f9e24a19ee4d16ba97110)
<details>
<summary>API 테스트 결과</summary>
</details>

Feature(HK-110): 키체인 수정을 위한 API 구현

---

src/main/java/kr/husk/application/auth/dto/ChangePasswordDto.java
src/main/java/kr/husk/application/auth/service/AuthService.java
src/main/java/kr/husk/domain/auth/exception/UserExceptionCode.java
src/main/java/kr/husk/presentation/api/AuthApi.java
src/main/java/kr/husk/presentation/rest/AuthController.java

- 비밀번호 변경 플로우에 따른 추가 API 구현
- `회원정보 수정(비밀번호 변경) 요청` → `현재 비밀번호 확인` → `새로운 비밀번호 및 새로운 비밀번호 확인`
- 위의 플로우에 따른 `현재 비밀번호 확인` API 필요성 확인.
- API 추가 구현으로 인한 역할 분리
- 기존: `비밀번호 변경 요청` → `현재 비밀번호 및 변경 비밀번호 동시 검증` → `비밀번호 변경`
- 현재: `비밀번호 변경 요청` → `현재 비밀번호 검증` → `변경 비밀번호 검증` → `비밀번호 변경` (별도로 분할하여 확인)
- 역할 분리에 따른 dto 객체 분리 (3fdd5001ca306b544c2f4d58c35d363533102f36)
- 별도의 API 및 비즈니스 로직 추가 (761493800473f1d5ff8dcb2d149985122172189c)
- 추가적으로 WAS에서도 현재 비밀번호와 변경할 비밀번호가 일치할 경우에 대한 예외 추가 및 예외 코드 추가(7ca8292151ef42b8997ea4d6cbc0694e65c7acf4)
- 얘기 나눴던대로 구현하였습니다. API에 대한 명세는 기존처럼 `swagger` 확인하시면 될 것 같습니다.
- 추후에 **질문사항, 필요하신 요구사항** 있으시면 코멘트나 스크럼 또는 연락주세요!
<details>
<summary>API 테스트</summary>
- 입력한 현재 비밀번호가 일치하지 않음
- 입력한 현재 비밀번호가 일치함
- 현재 비밀번호화 변경할 비밀번호가 일치함
</details>

Feature(HK-115): 비밀번호 변경 플로우에 따른 추가 API 구현

---

src/main/java/kr/husk/application/keychain/dto/KeyChainDto.java
src/main/java/kr/husk/domain/keychain/service/KeyChainService.java
src/main/java/kr/husk/presentation/api/KeyChainApi.java
src/main/java/kr/husk/presentation/rest/KeyChainController.java

- 서비스 기능 중 사용자가 등록한 키체인을 삭제하는 API 필요.
- 데이터 복구 및 무결성 유지를 위한 `soft delete`
- `Controller` 및 `Service` 계층에 비즈니스 로직 구현 (6f6e75b12ec85930474c8872a03d7d431ef8809f)
- `키체인 조회 API` 요청 시 삭제된 키체인을 필터링하여 삭제되지 않은 키체인만 반환하도록 함. (84c59597d8773714dbb159f9cfa0e40b7570ba72)
<details>
<summary>API 테스트</summary>
- 삭제 완료
- 삭제 중복 요청
- 1번 키페어 삭제 시 키페어 조회 요청에 대한 응답
</details>

Feature(HK-111): 키체인 삭제를 위한 API 구현

---

src/main/java/kr/husk/application/keychain/dto/KeyChainDto.java
src/main/java/kr/husk/common/service/EncryptionService.java
src/main/java/kr/husk/domain/keychain/service/KeyChainService.java
src/main/java/kr/husk/presentation/api/KeyChainApi.java
src/main/java/kr/husk/presentation/rest/KeyChainController.java

- `keychain` `content` 확인 로직
- `keychain` 조회를 통해 사용자가 `dashboard` 진입 시 자신이 등록한 `keychain` 확인 가능.
- 사용자가 등록한 `keychain`을 클릭하여 확인하여도 content는 `******` 와 같이 마스킹됨.
- `keychain`의 `content`를 확인하기 위한 API 필요
- 복호화를 위한 `decrypt()` 추가 (77c578096c7e266d88f9c8d97c2f9af58c3a0a96)
- 복호화 된 `keychain` 반환을 위한 dto 메소드 추가 (ec16d6cef936c0e22b6d50080e223525f3facea8)
- 복호화 API 구현 (05928e2ff61a76eff8b93725afe144935d0f4bf2)
<details>
<summary>API 테스트</summary>
- DB에 저장된 값
- 복호화 요청 결과
</details>

Feature(HK-114): 키체인 content 복호화를 위한 API 구현

---

src/main/java/kr/husk/application/connection/dto/ConnectionInfoDto.java
src/main/java/kr/husk/domain/connection/repository/ConnectionRepository.java
src/main/java/kr/husk/domain/connection/service/ConnectionService.java
src/main/java/kr/husk/domain/keychain/service/KeyChainService.java
src/main/java/kr/husk/presentation/api/ConnectionApi.java
src/main/java/kr/husk/presentation/rest/ConnectionController.java

- 사용자의 `keychain`을 통해 SSH 접속을 위한 `connection` 저장 API 필요.
- 저장된 `connection`을 통해서 사용자는 편리하게 SSH 접속이 가능.
- `SSH` 접속에 필요한 정보를 `DB`에 저장.
- 관련 `controller` 구현(cb9f7ba0ebf723a828d87f46c38a588ed9aba9ec) 및 `service` 내에 비즈니스 로직 구현(53c725b330de21870e4f42ec40a3c01f91fe45af)
- 기존에 `keychain`의 `content`를 입력하는 부분을 `keychain`의 `name` 입력하는 것으로 변경.
- 사용자는 `connection`을 생성하기 전 `keychain`을 미리 저장하여야 하는 것으로 함.
- 하지만 UX 관점에서 좋지 않다고 생각이 되어 향후 **_수정_** 될 수 있을 듯 합니다.
<details>
<summary>API 테스트 결과</summary>
</details>
- 오타가 있으면 말씀해주시면 감사하겠습니다. :)
- 궁금한 내용이 있다면 편하게 질문해주세요!

Feature(HK-107): 커넥션 저장을 위한 API 구현

---

build.gradle
src/main/java/kr/husk/infrastructure/config/WebSocketConfig.java
src/main/java/kr/husk/infrastructure/websocket/SshWebSocketHandler.java

- 웹 터미널을 통한 커넥션 접속을 위해 WebSocket 설정 필요.
- 대화형 웹 터미널을 위한 WebSocket 필요.
- 커넥션 접속을 위한 JSch를 이용한 WebSocket Handler 구현.
- JSch 및 WebSocket 사용을 위한 의존성 주입(f2875afb7ae24e4abed36933321845cc0361c54a)
- WebSocket 설정 파일 작성(70d7dee31d75d3255e394e9c0be834a2ed151335)
- WebSocket Handler 구현(12304d89f77c7c2a8ead9aa5a7fc4edbe36421b5)
- Handler에 구현된 부분에서 CI failed가 발생했었는데 이는 미리 작성해둔 코드가 있었는데 해당 PR에는 그 코드가 반영되지 않아서 오류가 발생한 것 입니다!
- PR이 커져서 분리하다보니 해당 부분을 놓쳤네요..😅
- 다음 PR에 올릴 예정이며, 현재는 주석 처리하여 CI 성공했습니다.

Chore(HK-132): 커넥션 접속을 위한 WebSocket 및 JSch 사전 설정

---

src/main/java/kr/husk/domain/connection/entity/Connection.java
src/main/java/kr/husk/domain/connection/exception/ConnectionExceptionCode.java
src/main/java/kr/husk/domain/connection/service/ConnectionService.java
src/main/java/kr/husk/infrastructure/websocket/SshWebSocketHandler.java
src/main/java/kr/husk/presentation/api/ConnectionApi.java
src/main/java/kr/husk/presentation/rest/ConnectionController.java

- 서비스 핵심 기능 이용을 위해서 사용자가 등록한 커넥션을 접속하기 위한 요청 API 필요.
- 대화형 웹 터미널 기능 이용을 위한 WebSocket을 활용한 핸들러 메소드 필요.
- JSch 및 WebSocket을 활용한 핸들러 구현(8a5bfcdafd22501253577032b608f956afb992de)
- 서비스 비즈니스 로직 구현(7abd087e9acb28ceeeb5e5b94b4c5a9504ab462e) 및 관련 예외 코드 추가(625ab01a5bcbcae4d3702a82adeeec470f6c433a)
- `Connection` Entity에서 getter 메소드 필요로 인해 `get{필드}()` 형식의 메소드를 만들었으나 어노테이션으로 변경(7c448432c64f4d9a2494f931a34e5dc88963df88)
- 대화형 웹 터미널을 위해선 웹 소켓 통신이 필수라고 합니다. 
- 해당 API 연동할 때, 소켓 통신을 활용하여 하는데, 이는 스크럼 때 정확하게 말씀드릴게요! 😄

Feature(HK-108): 커넥션 접속 요청 API 구현

---

src/main/java/kr/husk/domain/connection/entity/Connection.java
src/main/java/kr/husk/domain/connection/service/ConnectionService.java
src/main/java/kr/husk/domain/keychain/service/KeyChainService.java
src/main/java/kr/husk/presentation/api/ConnectionApi.java
src/main/java/kr/husk/presentation/rest/ConnectionController.java

- 사용자가 등록한 `Connection`의 수정을 위한 API 개발 필요.
- 사용자는 `Connection`을 잘못 등록 또는 수정이 필요한 경우 삭제 후 재등록할 필요가 없음.
- `Connection` 수정의 경우 `KeyChainName`을 변경할 시 기존에 사용자가 등록한 `KeyChain`을 기반으로 변경되어야 함.
- Controller 구현(c334b282e93953e68a600fbfbf5eab64ad64b88c), 비즈니스 로직 작성(f0597d9ed70f5edd165a2899e666cfdc7a297dce)
- `Connection Entity` 내에 `update` 메소드 추가(10f4fe0ab1f4f83227a965ca9165391e73f5cc7f)
- 이외에 `KeyChain` 관련 비즈니스 로직 처리 부분에 `@Transactional` 어노테이션을 추가했습니다. (cf5bb046f7da85ea6dbc7147ca4fa55f76cca6a8)
<details><summary>API 테스트 결과</summary>
</details>

Feature(HK-141): SSH Connection 수정을 위한 API 구현

---

build.gradle
src/main/java/kr/husk/infrastructure/config/SecurityConfig.java
src/main/java/kr/husk/infrastructure/websocket/SshWebSocketHandler.java

- 이전의 `JSch` 라이브러리의 경우 현재 업데이트가 진행되지 않을뿐더러 SSH 연결을 위해서는 실제 `.pem` 파일을 경로로 등록하여 사용해야 한다고 함.
- 안정적인 커넥션 기능 구현을 위한 `SSHJ` 라이브러리 채택.
- 따라서, `JSch` 라이브러리에서 `SSHJ` 라이브러리로 변환을 위한 코드 리팩토링 필요.
- 라이브러리 관련 의존성 수정(0fd6ea2b7a413e7e638969711b10fcde6537fdbc)
- SSH Connection 관련 Handler 서비스 로직 리팩토링(168dfd44ef344eda2803880864320e0fb511390a)
- 현재 원활한 작업을 위해 웹소켓 엔드포인트의 인증을 허용해놓은 상태입니다.
- FE에서는 시험 끝나고 새 스프린트 시작될 때, 어떤 작업을 하면 될지 얘기해보면 될 것 같습니다!
<details><summary>수정 후 연결 API 테스트</summary>
</details>

Refactor(HK-146): SSH Connection 연결을 위한 라이브러리 수정 및 리팩토링

---

src/main/java/kr/husk/application/connection/dto/ConnectionInfoDto.java
src/main/java/kr/husk/domain/connection/service/ConnectionService.java
src/main/java/kr/husk/presentation/api/ConnectionApi.java
src/main/java/kr/husk/presentation/rest/ConnectionController.java

- `Connection` 목록에서 특정 항목 선택 시 수정, 삭제, 조회를 위한 API 구현 필요성 대두.
- 서비스 이용의 편의 및 UX 향상을 위한 API 추가 필요.
- 기존의 조회 API에 대한 메소드명 수정 (`read` → `list`) & 세부 조회를 위한 비즈니스 로직 추가 (3025fcf084c3128dc41e22789ae3fb346adaf454)
- DTO 클래스 정의 (7910e198fc8c24cf3da9f9e01f9892631695c509)
- 혹시 추가적으로 구현이 필요하거나 반영이 필요한 사항이 있다면 말씀해주세요 😆
<details><summary>API 테스트</summary>
<p>
- 성공적으로 조회한 경우
- `connection id`가 틀린 경우
</p>
</details>

Feature(HK-154): Connection 세부 조회 API 구현
